# Generated by Django 5.0.3 on 2024-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_petprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='available_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
